package web01.src;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Date;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 * Servlet implementation class UserInfoView
 */
@WebServlet(name = "UserInfoViewServlet", urlPatterns = { "/user_info" })
public class UserInfoViewServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		PrintWriter out = response.getWriter();
		List<MemberVO> list = (List) request.getAttribute("list");
		
		out.print("<html>\r\n"
				+ "<head>\r\n"
				+ "<title>Insert title here</title>\r\n"
				+ "<link rel=\"stylesheet\" href=\"./css/SignUpForm.css\">\r\n"
				+ "<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n"
				+ "<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n"
				+ "<script>\r\n"
				+ "$(document).ready(function (){\r\n"
				+ "	$('#go_back').click(function (){\r\n"
				+ "		window.history.back();\r\n"
				+ "	}); \r\n"
				+ "});\r\n"
				+ "\r\n"
				+ "function setYear(year) {\r\n"
				+ "	var rrn = document.loginform.rrn;\r\n"
				+ "	var rrn_year = rrn.value;\r\n"
				+ "	if(rrn_year.length >= 2) {\r\n"
				+ "		rrn.value = year.value.substring(2) + rrn_year.substring(2);\r\n"
				+ "	}\r\n"
				+ "	else\r\n"
				+ "	rrn.value = year.value.substring(2);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "function setMonth(mon) {\r\n"
				+ "	var rrn = document.loginform.rrn;\r\n"
				+ "	var rrn_month = rrn.value;\r\n"
				+ "	if(rrn_month.length == 4) {\r\n"
				+ "		rrn.value = rrn_month.substring(0,2) + mon.value;\r\n"
				+ "	}\r\n"
				+ "	else if(rrn_month.length == 6) {\r\n"
				+ "		rrn.value = rrn_month.substring(0,2) + mon.value + rrn_month.substring(4,6);\r\n"
				+ "	}\r\n"
				+ "	else\r\n"
				+ "	rrn.value += mon.value;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "function setDay(day) {\r\n"
				+ "	var rrn = document.loginform.rrn;\r\n"
				+ "	var rrn_day = rrn.value;\r\n"
				+ "	if(rrn_day.length >= 6) {\r\n"
				+ "		rrn.value = rrn_day.substring(0,4) + day.value;\r\n"
				+ "	}\r\n"
				+ "	else\r\n"
				+ "	rrn.value += day.value; 		\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "function setRrn_2() {\r\n"
				+ "	var now = new Date();\r\n"
				+ "	var now_year = parseInt(now.getFullYear().toString().substring(2));\r\n"
				+ "	var bir_year = parseInt(document.loginform.year.value.substring(2));\r\n"
				+ "	var gender = document.loginform.gender.value;\r\n"
				+ "	var rrn_gen_temp = (gender == \"male\") ? [1,3] : [2,4];\r\n"
				+ "	var rrn_gen = (now_year >= bir_year) ? rrn_gen_temp[1] : rrn_gen_temp[0];\r\n"
				+ "	var rrn_2 = document.loginform.rrn_2;\r\n"
				+ "	console.log(now_year, bir_year, now_year >= bir_year, rrn_gen);\r\n"
				+ "	rrn_2.value = rrn_gen;\r\n"
				+ "	rrn_2.disabled=false;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "function setDateSelectBox(){\r\n"
				+ "	var now = new Date();\r\n"
				+ "	var now_year = now.getFullYear();\r\n"
				+ "	var selbox_year = document.loginform.year;\r\n"
				+ "	var selbox_day = document.loginform.day;\r\n"
				+ "	var selbox_month = document.loginform.month;\r\n"
				+ "	\r\n"
				+ "	var optgp_year = document.createElement(\"optgroup\");\r\n"
				+ "	optgp_year.label = \"출생년도\";\r\n"
				+ "	for(var i = now_year; i >= 1900; i--){\r\n"
				+ "		var option = document.createElement(\"option\");\r\n"
				+ "		option.value = i.toString();\r\n"
				+ "		option.text = i.toString()+\"년\";\r\n"
				+ "		optgp_year.appendChild(option);\r\n"
				+ "	}\r\n"
				+ "	selbox_year.appendChild(optgp_year);\r\n"
				+ "	\r\n"
				+ "	var optgp_day = document.createElement(\"optgroup\");\r\n"
				+ "	optgp_day.label = \"출생일\";\r\n"
				+ "	for(var i = 1; i <= 31; i++){\r\n"
				+ "		var option = document.createElement(\"option\");\r\n"
				+ "		option.value = i.toString().padStart(2, \"0\");\r\n"
				+ "		option.text = i.toString().padStart(2, \"0\")+\"일\";\r\n"
				+ "		optgp_day.appendChild(option);\r\n"
				+ "	}\r\n"
				+ "	selbox_day.appendChild(optgp_day);\r\n"
				+ "	\r\n"
				+ "	var optgp_month = document.createElement(\"optgroup\");\r\n"
				+ "	optgp_month.label = \"출생월\";\r\n"
				+ "	for(var i = 1; i <= 12; i++){\r\n"
				+ "		var option = document.createElement(\"option\");\r\n"
				+ "		option.value = i.toString().padStart(2, \"0\");\r\n"
				+ "		option.text = i.toString().padStart(2, \"0\")+\"월\";\r\n"
				+ "		optgp_month.appendChild(option);\r\n"
				+ "	}\r\n"
				+ "	selbox_month.appendChild(optgp_month);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "function setMail(mail3) {\r\n"
				+ "	var mail2 = document.loginform.mail2;\r\n"
				+ "	if(mail3.selectedIndex == 0) {\r\n"
				+ "		mail2.value = \"\";\r\n"
				+ "	}\r\n"
				+ "	else {\r\n"
				+ "		mail2.value = mail3.value;\r\n"
				+ "	}\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "//본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n"
				+ "function set_postcode() {\r\n"
				+ "	new daum.Postcode({\r\n"
				+ "        oncomplete: function(data) {\r\n"
				+ "            // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n"
				+ "\r\n"
				+ "            // 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\r\n"
				+ "            // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n"
				+ "            var roadAddr = data.roadAddress; // 도로명 주소 변수\r\n"
				+ "            var extraRoadAddr = ''; // 참고 항목 변수\r\n"
				+ "\r\n"
				+ "            // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n"
				+ "            // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n"
				+ "            if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n"
				+ "              	extraRoadAddr += data.bname;\r\n"
				+ "            }\r\n"
				+ "            // 건물명이 있고, 공동주택일 경우 추가한다.\r\n"
				+ "            if(data.buildingName !== '' && data.apartment === 'Y'){\r\n"
				+ "               extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n"
				+ "            document.getElementById('postcode').value = data.zonecode;\r\n"
				+ "            document.getElementById(\"roadAddr\").value = roadAddr;\r\n"
				+ "             document.getElementById(\"jibunAddr\").value = data.jibunAddress;\r\n"
				+ "                \r\n"
				+ "        }\r\n"
				+ "    }).open();\r\n"
				+ "}\r\n"
				+ "</script>\r\n");
		
		MemberVO memberVO = list.get(0);
		String MEMBER_ID =  memberVO.getMEMBER_ID();
		String MEMBER_PW = memberVO.getMEMBER_PW();
		String MEMBER_NAME = memberVO.getMEMBER_NAME();
		String MEMBER_GENDER = memberVO.getMEMBER_GENDER();
		String TEL1 = memberVO.getTEL1();
		String TEL2 = memberVO.getTEL2();
		String TEL3 = memberVO.getTEL3();
		String SMSSTS_YN = memberVO.getSMSSTS_YN();
		String EMAIL1 = memberVO.getEMAIL1();
		String EMAIL2 = memberVO.getEMAIL2();
		String EMAILSTS_YN = memberVO.getEMAILSTS_YN();
		String POSTCODE = memberVO.getPOSTCODE();
		String ROADADDRESS = memberVO.getROADADDRESS();
		String JIBUNADDRESS = memberVO.getJIBUNADDRESS();
		String DETAILADDRESS = memberVO.getDETAILADDRESS();	
		String MEMBER_BIRTH_Y = memberVO.getMEMBER_BIRTH_Y();
		String MEMBER_BIRTH_M = memberVO.getMEMBER_BIRTH_M();
		String MEMBER_BIRTH_D = memberVO.getMEMBER_BIRTH_D();
		String MEMBER_BIRTH_GN = memberVO.getMEMBER_BIRTH_GN();
		int DEPTNO = memberVO.getDEPTNO();
		String DNAME = memberVO.getDNAME();
		Date JOINDATE = memberVO.getJOINDATE();
		String RRN_FRONT = memberVO.getRRN_FRONT();
		String RRN_BACK = memberVO.getRRN_BACK();
		
		out.print("<script>\r\n"
				+ "	$(document).ready(function() {\r\n"
				+ "		setDateSelectBox();\r\n"
				+ "		var options = $('#phone1').find('option').map(function() {\r\n"
				+ "	      return $(this).val();\r\n"
				+ "		}).get();\r\n"
				+ "		var birth_y = $('#year').find('option').map(function() {\r\n"
				+ "		      return $(this).val();\r\n"
				+ "		}).get();\r\n"
				+ "		var birth_m = $('#month').find('option').map(function() {\r\n"
				+ "		      return $(this).val();\r\n"
				+ "		}).get();\r\n"
				+ "		var birth_d = $('#day').find('option').map(function() {\r\n"
				+ "		      return $(this).val();\r\n"
				+ "		}).get();\r\n"
				+ "	console.log(options);\r\n"
				+ "	if(options.includes(\""+TEL1+"\")) {\r\n"
				+ "		$(\"#phone1\").val(\""+TEL1+"\").prop(\"selected\", true);\r\n"
				+ "		$(\"#phone1\").prop(\"disabled\", true);\r\n"
				+ "	}\r\n"
				+ "	\r\n"
				+ "	if(\""+SMSSTS_YN+"\"==\"Y\") {\r\n"
				+ "		$(\"#smssts\").prop(\"checked\", true);\r\n"
				+ "		$(\"#smssts\").prop(\"disabled\", true);\r\n"
				+ "	} else {\r\n"
				+ "		$(\"#smssts\").prop(\"disabled\", true);\r\n"
				+ "	}\r\n"
				+ "	\r\n"
				+ "	if(\""+EMAILSTS_YN+"\"==\"Y\") {\r\n"
				+ "		$(\"#emailsts\").prop(\"checked\", true);\r\n"
				+ "		$(\"#emailsts\").prop(\"disabled\", true);\r\n"
				+ "	} else {\r\n"
				+ "		$(\"#emailsts\").prop(\"disabled\", true);\r\n"
				+ "	}\r\n"
				+ "	\r\n"
				+ "	if(\""+MEMBER_GENDER+"\"==\"male\") {\r\n"
				+ "		$(\"#male\").prop(\"checked\", true);\r\n"
				+ "		$(\"#female\").prop(\"disabled\", true);\r\n"
				+ "	}\r\n"
				+ "	else {\r\n"
				+ "		$(\"#female\").prop(\"checked\", true);\r\n"
				+ "		$(\"#male\").prop(\"disabled\", true);\r\n"
				+ "	}\r\n"
				+ "	\r\n"
				+ "	if(\""+MEMBER_BIRTH_GN+"\"==\"sola\") {\r\n"
				+ "		$(\"#sola\").prop(\"checked\", true);\r\n"
				+ "		$(\"#lunar\").prop(\"disabled\", true);\r\n"
				+ "	}\r\n"
				+ "	else {\r\n"
				+ "		$(\"#lunar\").prop(\"checked\", true);\r\n"
				+ "		$(\"#sola\").prop(\"disabled\", true);\r\n"
				+ "	}\r\n"
				+ "	\r\n"
				+ "	$('#deptno').val(\""+DEPTNO+"\").prop(\"selected\", true);\r\n"
				+ "	$(\"#selected-deptno\").val($(\"#deptno option:selected\").text());\r\n"
				+ "	\r\n"
				+ "	$('#year').val(\""+MEMBER_BIRTH_Y+"\").prop(\"selected\", true);\r\n"
				+ "	console.log(birth_y);\r\n"
				+ "	$('#month').val(\""+MEMBER_BIRTH_M+"\").prop(\"selected\", true);\r\n"
				+ "	console.log(birth_m);\r\n"
				+ "	$('#day').val(\""+MEMBER_BIRTH_D+"\").prop(\"selected\", true);\r\n"
				+ "	console.log(birth_d);\r\n"
				+ "	setYear(year);\r\n"
				+ "	setMonth(month);\r\n"
				+ "	setDay(day);\r\n"
				+ "	$('#loginform').on('submit', function() {\r\n"
				+ "		$(\"#phone1\").prop(\"disabled\", false);\r\n"
				+ "		$(\"#mail3\").prop(\"disabled\", false);\r\n"
				+ "		$(\"#smssts\").prop(\"disabled\", false);\r\n"
				+ "		$(\"#emailsts\").prop(\"disabled\", false);\r\n"
				+ "	    $('#year').prop('disabled', false);\r\n"
				+ "	    $('#month').prop('disabled', false);\r\n"
				+ "	    $('#day').prop('disabled', false);\r\n"
				+ "	    $('#deptno').prop('disabled', false);\r\n"
				+ "	});\r\n"
				+ "	});\r\n"
				+ "\r\n"
				+ "</script>"
				+ "\r\n");
			
		out.print("</head>\r\n"
				+ "<body>\r\n"
				+ "	\r\n"
				+ "	<form id=\"loginform\" name=\"loginform\" action=\"./AlterUserInfo.jsp\" method=\"GET\" onSubmit=\"return validateForm()\" accept-charset=\"UTF-8\">\r\n"
				+ "		<table class=\"form-table\">\r\n"
				+ "			<tr> \r\n"
				+ "				<th class=\"title\" colspan=\"2\">내 정보</th>\r\n"
				+ "			</tr>\r\n"
				+ "			<tr>\r\n"
				+ "				<td class=\"title\">아이디</td>\r\n"
				+ "				<td>\r\n"
				+ "					<input type=\"text\" name=\"id\" id=\"id\" value=\""+MEMBER_ID+"\" readonly>\r\n"
				+ "				</td>\r\n"
				+ "			</tr>\r\n"
				+ "			<tr>\r\n"
				+ "				<td class=\"title\">비밀번호</td>\r\n"
				+ "				<td><input type=\"text\" name=\"password\" value=\""+MEMBER_PW+"\" readonly></td>\r\n"
				+ "			</tr>\r\n"
				+ "			<tr>\r\n"
				+ "				<td class=\"title\">이름</td>\r\n"
				+ "				<td><input type=\"text\" name=\"name\" value=\""+MEMBER_NAME+"\" readonly></td>\r\n"
				+ "			</tr>\r\n"
				+ "			<tr>\r\n"
				+ "				<td class=\"title\">전화번호</td>\r\n"
				+ "				<td>\r\n"
				+ "					<select id=\"phone1\" name=\"phone1\">\r\n"
				+ "						<option>010</option>\r\n"
				+ "						<option>011</option>\r\n"
				+ "						<option>016</option>\r\n"
				+ "						<option>017</option>\r\n"
				+ "						<option>018</option>\r\n"
				+ "						<option>019</option>\r\n"
				+ "					</select>\r\n"
				+ "					<span>-</span>\r\n"
				+ "					<input type=\"text\" name=\"phone2\" value=\""+TEL2+"\" maxlength=\"4\" style=\"width:80px;\" readonly>\r\n"
				+ "					<input type=\"text\" name=\"phone3\" value=\""+TEL3+"\" maxlength=\"4\" style=\"width:80px;\" readonly>\r\n"
				+ "					<br>\r\n"
				+ "					<input id = \"smssts\" type=\"checkbox\" name=\"smssts\" value=\"Y\" readonly>\r\n"
				+ "					<input id = \"hidden-smssts\" type=\"hidden\" name=\"smssts\" value=\"N\">\r\n"
				+ "					<label for= \"smssts\"><span>쇼핑몰에서 발송하는 SMS 소식을 수신합니다.</span></label> \r\n"
				+ "				</td>\r\n"
				+ "			</tr>\r\n"
				+ "			<tr>\r\n"
				+ "				<td class=\"title\">이메일</td>\r\n"
				+ "				<td>\r\n"
				+ "					<input type=\"text\" name=\"mail1\" value=\""+EMAIL1+"\" style=\"width:100px; text-align:right;\" readonly>\r\n"
				+ "					<span>@</span>\r\n"
				+ "					<input type=\"text\" name=\"mail2\" value=\""+EMAIL2+"\" style=\"width:100px;\" readonly>\r\n"
				+ "					<select id=\"mail3\" name=\"mail3\" onchange=\"setMail(this)\" disabled>\r\n"
				+ "						<option>직접 입력</option>\r\n"
				+ "						<option>naver.com</option>\r\n"
				+ "						<option>gmail.com</option>\r\n"
				+ "						<option>nate.com</option>\r\n"
				+ "						<option>daum.net</option>\r\n"
				+ "					</select>\r\n"
				+ "					<br>\r\n"
				+ "					<input id = \"emailsts\" type=\"checkbox\" name=\"emailsts\" value=\"Y\" readonly>\r\n"
				+ "					<input id = \"hidden-emailsts\" type=\"hidden\" name=\"emailsts\" value=\"N\">\r\n"
				+ "					<label for= \"emailsts\"><span>쇼핑몰에서 발송하는 e-mail을 수신합니다.</span></label> \r\n"
				+ "					</td>\r\n"
				+ "			</tr>\r\n"
				+ "			<tr>\r\n"
				+ "				<td class=\"title\">부서</td>\r\n"
				+ "				<td>\r\n"
				+ "					<select name=\"deptno\" id=\"deptno\" disabled>\r\n"
				+ "						<option value=\""+DEPTNO +"\">"+DNAME +"</option>\r\n"
				+ "					</select>\r\n"
				+ "					부서:\r\n"
				+ "					<input type=\"text\" name=\"dname\" id=\"selected-deptno\" readonly>\r\n"
				+ "					</td>\r\n"
				+ "			</tr>\r\n"
				+ "			<tr>\r\n"
				+ "				<td class=\"title\">성별</td>\r\n"
				+ "				<td>\r\n"
				+ "					<input id=\"male\" type=\"radio\" name=\"gender\" value=\"male\" onchange=\"setRrn_2()\" readonly>\r\n"
				+ "					<label for=\"male\">남성</label>\r\n"
				+ "					<input id=\"female\" type=\"radio\" name=\"gender\" value=\"female\" onchange=\"setRrn_2()\" readonly>\r\n"
				+ "					<label for=\"female\">여성</label>\r\n"
				+ "				</td>		\r\n"
				+ "			</tr>\r\n"
				+ "			<tr>\r\n"
				+ "				<td class=\"title\">생년월일</td>\r\n"
				+ "				<td>\r\n"
				+ "					<select id=\"year\" name=\"year\" onchange=\"setYear(this), setRrn_2()\" disabled>\r\n"
				+ "					</select>\r\n"
				+ "					<select id=\"month\" name=\"month\" onchange=\"setMonth(this)\" disabled>\r\n"
				+ "					</select>\r\n"
				+ "					<select id=\"day\" name=\"day\" onchange=\"setDay(this)\" disabled>\r\n"
				+ "					</select>\r\n"
				+ "					<input id=\"sola\" type=\"radio\" name=\"calendar\" value=\"sola\">\r\n"
				+ "					<label for=\"sola\">양력</label>\r\n"
				+ "					<input id=\"lunar\" type=\"radio\" name=\"calendar\" value=\"lunar\">\r\n"
				+ "					<label for=\"lunar\">음력</label>\r\n"
				+ "				</td>\r\n"
				+ "			</tr>\r\n"
				+ "			<tr>\r\n"
				+ "				<td class=\"title\">주민등록번호</td>\r\n"
				+ "				<td><input type=\"text\" name=\"rrn\" value=\"000000\" style=\"width:80px; text-align:right;\" readonly> \r\n"
				+ "				<b>-</b> \r\n"
				+ "				<input type=\"text\" name=\"rrn_2\" value=\""+RRN_BACK +"\" style=\"width:80px;\" readonly></td>\r\n"
				+ "			</tr>\r\n"
				+ "			<tr>\r\n"
				+ "				<td class=\"title\">주소</td>\r\n"
				+ "				<td>\r\n"
				+ "				<input id=\"postcode\" type=\"text\" name=\"postcode\" value=\""+POSTCODE +"\" readonly><br>\r\n"
				+ "					<label for=\"roadAddr\">도로명 주소:</label><br>\r\n"
				+ "					<input id=\"roadAddr\" type=\"text\" name=\"roadAddr\" value=\""+ROADADDRESS +"\" style=\"width:300px;\" readonly><br>\r\n"
				+ "					<label for=\"jibunAddr\">지번 주소:</label><br>\r\n"
				+ "					<input id=\"jibunAddr\" type=\"text\" name=\"jibunAddr\" value=\""+JIBUNADDRESS +"\" style=\"width:300px;\" readonly><br>\r\n"
				+ "					<label for=\"detailAddr\">상세 주소:</label><br>\r\n"
				+ "					<input id=\"detailAddr\" type=\"text\" name=\"detailAddr\" value=\""+DETAILADDRESS +"\" value=\"\" readonly>\r\n"
				+ "				</td>\r\n"
				+ "			</tr>\r\n"
				+ "			<tr align=\"right\">\r\n"
				+ "				<td class=\"title\" colspan=\"2\"><input type=\"submit\" value=\"수정\"><input type=\"button\" value=\"돌아가기\" id='go_back'></td>\r\n"
				+ "			</tr>\r\n"
				+ "		</table>\r\n"
				+ "	</form>\r\n"
				+ "</body>\r\n"
				+ "</html>");
	}

}
