package web01.src;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Date;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class ViewServlet
 */
@WebServlet("/show_member_view")
public class ViewServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		PrintWriter out = response.getWriter();
		List<MemberVO> list = (List) request.getAttribute("memberList");
		
		out.print("<html>"
				+ "<head>"
				+"<style>"
				+ ".searchDiv {"
				+ "	float:right;"
				+ "	clear:right;"
				+ "}"
				+ ""
				+ ".title {"
				+ "	text-align:center;"
				+ "}"
				+ ""
				+ ".memtable {"
				+ "	margin-top:20px;"
				+ "	clear:right;"
				+ "	float:right;"
				+ "}"
				+ ""
				+ "section {"
				+ "	margin: 0 auto;"
				+ "	width:90%;"
				+ "}"
				+ ""
				+ "table {"
				+ "word-break: keep-all;"
				+ "}"
				+ ""
				+ "#searchmem {"
				+ "	float:right;"
				+ "	clear:right;"
				+ "}"
				+ ""
				+ "#first-search-bar {"
				+ "	float:right;"
				+ "	clear:right;"
				+ "}"
				+ "</style>"
				+ "<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>"
				+ "<script>"
				+ "		function updateMem(member_id, member_pw)\r\n"
				+ "		{\r\n"
				+ "			alert(\"update\");	\r\n"
				+ "			//alert(id);\r\n"
				+ "			\r\n"
				+ "			window.location.href=\"/Web01/user/AlterUserInfo.jsp?member_id=\"+member_id+\"&member_pw=\"+member_pw;\r\n"
				+ "			\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "		function deleteMem(member_id)\r\n"
				+ "		{\r\n"
				+ "			alert(\"delete\");\r\n"
				+ "			//alert(id);\r\n"
				+ "			\r\n"
				+ "			window.location.replace(\"/Web01/show_member?member_id=\"+member_id+\"&command=delete\");\r\n"
				+ "		}"
				+ "$(document).ready(function() {"
				+ "var count = 0;\r\n"
				+ "		$('#show-all').click(function() {\r\n"
				+ "			alert(\"show all of user\");\r\n"
				+ "			window.location.href=\"show_member\";\r\n"
				+ "		});\r\n"
				+ "		\r\n"
				+ "		$('#tag-add').click(function() {\r\n"
				+ "				count++;"
				+ "				let countStr = count.toString().padStart(2, \"0\");\r\n"
				+ "				\r\n"
				+ "				var obj = document.getElementById(\"search-form\");\r\n"
				+ "				var hidden_count = document.getElementById(\"count\");\r\n"
				+ "				var searchDiv = document.createElement(\"div\");\r\n"
				+ "				var newTag = document.createElement(\"select\");\r\n"
				+ "				var tagNum = document.createElement(\"span\");\r\n"
				+ "				var tags = document.getElementsByName(\"search-opt\");\r\n"
				+ "				var and = document.createElement('input');\r\n"
				+ "				var andlabel = document.createElement('label');\r\n"
				+ "				var andlabeltext = document.createTextNode('AND');\r\n"
				+ "				var or = document.createElement('input');\r\n"
				+ "				var orlabel = document.createElement('label');\r\n"
				+ "				var orlabeltext = document.createTextNode('OR');\r\n"
				+ "				var oneSpace = document.createElement(\"span\");\r\n"
				+ "				var oneSpace2 = document.createElement(\"span\");\r\n"
				+ "				var text = document.createElement('input');\r\n"
				+ "				var delTag = document.createElement('input');\r\n"
				+ "/*--------------------------------------------------------------------------*/				\r\n"
				+ "				searchDiv.setAttribute(\"class\", \"searchDiv\"); \r\n"
				+ "				searchDiv.setAttribute(\"id\", \"searchDiv\"+count); \r\n"
				+ "				\r\n"
				+ "				newTag.setAttribute(\"id\", \"search-opt\"+count);\r\n"
				+ "				newTag.setAttribute(\"name\", \"search-opt\");\r\n"
				+ "/*--------------------------------------------------------------------------*/				\r\n"
				+ "				and.type = 'radio';\r\n"
				+ "				and.name = 'and-or'+count;\r\n"
				+ "				and.id = 'and'+count;\r\n"
				+ "				and.value = 'and';\r\n"
				+ "				and.checked = true;\r\n"
				+ "				andlabel.htmlFor = 'and'+count;\r\n"
				+ "				andlabel.appendChild(andlabeltext);\r\n"
				+ "				\r\n"
				+ "			    or.type = 'radio';\r\n"
				+ "			    or.name = 'and-or'+count;\r\n"
				+ "			    or.id = 'or'+count;\r\n"
				+ "			    or.value = 'or';			\r\n"
				+ "				orlabel.htmlFor = 'or'+count;							 \r\n"
				+ "			    orlabel.appendChild(orlabeltext);\r\n"
				+ "			    \r\n"
				+ "			    text.type = 'text';\r\n"
				+ "				text.name = 'search-text';\r\n"
				+ "				text.id = 'search-text'+count;\r\n"
				+ "				\r\n"
				+ "				delTag.type = 'button';\r\n"
				+ "				delTag.id = 'delete-tag';\r\n"
				+ "				delTag.value = '조건 삭제';\r\n"
				+ "				\r\n"
				+ "/*--------------------------------------------------------------------------*/\r\n"
				+ "				tagNum.innerHTML = \"<br><b>+ 조건 \"+countStr+\"</b>&nbsp;\"\r\n"
				+ "				oneSpace.innerHTML = \"&nbsp;\"\r\n"
				+ "				oneSpace2.innerHTML = \"&nbsp;\"\r\n"
				+ "/*--------------------------------------------------------------------------*/				\r\n"
				+ "				\r\n"
				+ "				//newDiv.style.backgroundColor = \"yellow\";\r\n"
				+ "				\r\n"
				+ "				for(var i = 0; i < tags[0].length; i++){\r\n"
				+ "					let opt = document.createElement(\"option\");\r\n"
				+ "		    		opt.value = tags[0].options[i].value;\r\n"
				+ "		    		opt.text = tags[0].options[i].text;\r\n"
				+ "		    		newTag.appendChild(opt);\r\n"
				+ "				}\r\n"
				+ "				\r\n"
				+ "				obj.appendChild(searchDiv);				\r\n"
				+ "				searchDiv.appendChild(tagNum);\r\n"
				+ "				searchDiv.appendChild(and);\r\n"
				+ "				searchDiv.appendChild(andlabel);\r\n"
				+ "				searchDiv.appendChild(or);\r\n"
				+ "				searchDiv.appendChild(orlabel);\r\n"
				+ "				searchDiv.appendChild(oneSpace);\r\n"
				+ "				searchDiv.appendChild(newTag);\r\n"
				+ "				searchDiv.appendChild(oneSpace2);\r\n"
				+ "				searchDiv.appendChild(text);\r\n"
				+ "				searchDiv.appendChild(delTag);\r\n"
				+ "				\r\n"
				+ "				delTag.onclick = function() {\r\n"
				+ "					p = this.parentElement;\r\n"
				+ "					p.remove();\r\n"
				+ "				}\r\n"
				+ "				// 익명 함수 : 바로 그 이벤트를 실행하기위해 이름을 정하지 않고 바로실행\r\n"
				+ "		//		newDiv.onclick = function(){\r\n"
				+ "		//		let p = this.parentElement; //부모 HTML 태그요소\r\n"
				+ "		//		p.removeChild(this); // 자신을 부모 태그로 부터 제거\r\n"
				+ "		//		}\r\n"
				+ "				\r\n"
				+ "				hidden_count.value = count;\r\n"
				+ "		});\r\n"
				+ "});"
				+ "</script>"
				+ "</head>" 
				+"<body>");
		out.print("<div class=\"page\">"
				+ "		<header>"
				+ "		<h1 class=\"title\">전체 회원 정보</h1>"
				+ "		</header>"
				+ "		<section>"
				+ "			<article>"
				+ "				<div id=\"searchmem\">"
				+ "					<form id=\"search-form\" action=\"show_member\">"
				+ "						<div id=\"first-search-bar\">"
				+ "						<span><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;검색</b></span>"
				+ "						<select name=\"search-opt\">"
				+ "							<option value=\"MEMBER_ID\">아이디</option>"
				+ "							<option value=\"MEMBER_PW\">비밀번호</option>"
				+ "							<option value=\"MEMBER_NAME\">이름</option>"
				+ "							<option value=\"MEMBER_GENDER\">성별</option>"
				+ "							<option value=\"TEL1,TEL2,TEL3\">전화번호</option>"
				+ "							<option value=\"SMSSTS_YN\">문자 수신 동의 여부</option>"
				+ "							<option value=\"EMAIL1,EMAIL2\">이메일</option>"
				+ "							<option value=\"EMAILSTS_YN\">이메일 수신 동의 여부</option>"
				+ "							<option value=\"POSTCODE\">우편 번호</option>"
				+ "							<option value=\"ROADADDRESS\">도로명 주소</option>"
				+ "							<option value=\"JIBUNADDRESS\">지번 주소</option>"
				+ "							<option value=\"DETAILADDRESS\">상세 주소</option>"
				+ "							<option value=\"MEMBER_BIRTH_Y,MEMBER_BIRTH_M,MEMBER_BIRTH_D\">생년월일</option>"
				+ "							<option value=\"MEMBER_BIRTH_GN\">양력/음력</option>"
				+ "							<option value=\"JOINDATE\">가입 날짜</option>"
				+ "							<option value=\"DNAME\">부서</option>"
				+ "						</select>"
				+ "						<input type=\"text\" name=\"search-text\">"
				+ "						<input type=\"submit\" id=\"search-btn\" value=\"검색\">"
				+ "						<input type=\"button\" id=\"tag-add\" value=\"조건 추가\">"
				+ "						<input type=\"button\" id=\"show-all\" value=\"전체 출력\">"
				+ "						<input type=\"hidden\" name=\"count\" id=\"count\">"
				+ "						<input type=\"hidden\" name=\"command\" value=\"search\">"
				+ "						</div>"
				+ "					</form>"
				+ "				</div>"
				+ "			</article>");
		out.print("			<article>"
				+ "					<div class=\"memtable\">"
				+ "						<table border='1' style='border-collapse: collapse;'>"
				+ "							<tr>"
				+ "								<th><span>아이디</span></th>"
				+ "								<th><span>비밀번호</span></th>"
				+ "								<th><span>이름</span></th>"
				+ "								<th><span>성별</span></th>"
				+ "								<th><span>전화번호</span></th>"
				+ "								<th><span>문자 수신 동의 여부</span></th>"
				+ "								<th><span>이메일</span></th>"
				+ "								<th><span>이메일 수신 동의 여부</span></th>"
				+ "								<th><span>우편 번호</span></th>"
				+ "								<th><span>도로명 주소</span></th>"
				+ "								<th><span>지번 주소</span></th>"
				+ "								<th><span>상세 주소</span></th>"
				+ "								<th><span>생년월일</span></th>"
				+ "								<th><span>양력/음력</span></th>"
				+ "								<th><span>가입 날짜</span></th>"
				+ "								<th><span>부서</span></th>"
				+ "								<th><span>정보 갱신</span></th>"
				+ "								<th><span>정보 삭제</span></th>"
				+ "						</tr>");
				
		for(int i= 0; i < list.size(); i++) {
			MemberVO memberVO = list.get(i);
			String MEMBER_ID =  memberVO.getMEMBER_ID();
			String MEMBER_PW = memberVO.getMEMBER_PW();
			String MEMBER_NAME = memberVO.getMEMBER_NAME();
			String MEMBER_GENDER = memberVO.getMEMBER_GENDER();
			String tel = memberVO.getTEL1()+"-"+memberVO.getTEL2()+"-"+memberVO.getTEL3();
			String SMSSTS_YN = memberVO.getSMSSTS_YN();
			String email = memberVO.getEMAIL1()+"@"+memberVO.getEMAIL2();
			String EMAILSTS_YN = memberVO.getEMAILSTS_YN();
			String POSTCODE = memberVO.getPOSTCODE();
			String ROADADDRESS = memberVO.getROADADDRESS();
			String JIBUNADDRESS = memberVO.getJIBUNADDRESS();
			String DETAILADDRESS = memberVO.getDETAILADDRESS();	
			String birth_date = memberVO.getMEMBER_BIRTH_Y()+"-"+memberVO.getMEMBER_BIRTH_M()+"-"+memberVO.getMEMBER_BIRTH_D();
			String MEMBER_BIRTH_GN = memberVO.getMEMBER_BIRTH_GN();
			int DEPTNO = memberVO.getDEPTNO();
			String DNAME = memberVO.getDNAME();
			Date JOINDATE = memberVO.getJOINDATE();
			System.out.println(MEMBER_ID+" "+MEMBER_PW+" "+MEMBER_NAME+" "+MEMBER_GENDER+" "+tel+" "+SMSSTS_YN+" "+email+" "+EMAILSTS_YN+" "+POSTCODE+" "+ROADADDRESS+" "+JIBUNADDRESS+" "+DETAILADDRESS
					+" "+DETAILADDRESS+" "+birth_date+" "+MEMBER_BIRTH_GN+" "+DEPTNO+" "+DNAME+" "+JOINDATE);
			out.print("					<tr align='center'>"
					+ "						<td>"+MEMBER_ID+"</td>"
					+ "						<td>"+MEMBER_PW+"</td>"
					+ "						<td>"+MEMBER_NAME+"</td>"
					+ "						<td>"+MEMBER_GENDER+"</td>"
					+ "						<td>"+tel+"</td>"
					+ "						<td>"+SMSSTS_YN+"</td>"
					+ "						<td>"+email+"</td>"
					+ "						<td>"+EMAILSTS_YN+"</td>"
					+ "						<td>"+POSTCODE+"</td>"
					+ "						<td>"+ROADADDRESS+"</td>"
					+ "						<td>"+JIBUNADDRESS+"</td>"
					+ "						<td>"+DETAILADDRESS+"</td>"
					+ "						<td>"+birth_date+"</td>"
					+ "						<td>"+MEMBER_BIRTH_GN+"</td>"
					+ "						<td>"+JOINDATE+"</td>"
					+ "						<td>"+DNAME+"</td>"
					+ "						<td><input type=button value=Update onClick='updateMem(\""+MEMBER_ID+"\", \""+MEMBER_PW+"\");'></td>\r\n"
					+ "						<td><input type=button value=Delete onClick='deleteMem(\""+MEMBER_ID+"\");'></td>"
					+ "					</tr>"); 
		}
		out.print("					</table>"
				+ "				</div>"
				+ "			</article>"
				+ "		</section>"
				+ "	</div>"
				+ "</body>"
				+ "</html>");
	}
}
